User:
  actAs: [Timestampable]
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name: string
    age: integer
    driverLicense: boolean
    
Car:
  actAs: [Timestampable]
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    brand: string
    ps: integer
    ownerId: integer
  relations:
    Owner:
      class: User
      foreign: id
      local: ownerId
      foreignAlias: Cars